name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      CI: false 
      
    steps:
      - uses: actions/checkout@v3
      
      - name: List of directories
        run: ls
        
      - name: Change Directory to persona-prep
        run: cd persona-prep
      
      - name: Install Dependencies
        working-directory: persona-prep
        run: npm ci

      - name: Build
        working-directory: persona-prep
        run: npm run build

      - name: Set CI to false and Deploy to Firebase Hosting
        
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PERSONAPREP }}'
          entryPoint: './persona-prep/firebase.json'
          channelId: live
          projectId: personaprep
          run: |
            export CI=false
            # Additional environment variables or commands if needed
            node your_script.js

        

       
